# Generated by Django 5.2.3 on 2025-08-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='descripcion',
            field=models.CharField(default='Aporte de capital', max_length=200),
        ),
        migrations.AddField(
            model_name='capital',
            name='tipo',
            field=models.CharField(choices=[('aporte', 'Aporte'), ('retiro', 'Retiro')], default='aporte', max_length=10),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10),
        ),
    ]
