# Generated by Django 5.2.3 on 2025-08-06 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_capital_descripcion_capital_tipo_gasto_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA pagado', max_digits=10),
        ),
        migrations.AddField(
            model_name='compra',
            name='monto_neto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto sin IVA', max_digits=10),
        ),
        migrations.AddField(
            model_name='compra',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=2, default=12, help_text='Tasa de IVA (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA calculado', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_neto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto sin IVA', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=2, default=12, help_text='Tasa de IVA (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='compra',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto total con IVA', max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto total con IVA', max_digits=10),
        ),
        migrations.CreateModel(
            name='PagoCuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cuenta_por_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='empresa.cuentaporcobrar')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoCuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('cuenta_por_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='empresa.cuentaporpagar')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
