# Generated by Django 5.2.3 on 2025-08-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_add_iva_and_payment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto inicial para préstamos o deudas', max_digits=12),
        ),
    ]
