# Generated by Django 5.2.3 on 2025-08-06 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_cuentacontable_monto_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_pagar', to='empresa.compra'),
        ),
    ]
