# Generated by Django 5.2.3 on 2025-08-08 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_cuentaporpagar_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(help_text='Nombre del tipo de servicio (ej: Consultoría, Mantenimiento, Diseño)', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del servicio')),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del servicio', max_digits=10)),
                ('costo_directo', models.DecimalField(decimal_places=2, default=0, help_text='Costo directo asociado al servicio (materiales, subcontratación, etc.)', max_digits=10)),
                ('tiempo_estimado', models.PositiveIntegerField(blank=True, help_text='Tiempo estimado en horas para completar el servicio', null=True)),
                ('unidad_medida', models.CharField(default='Servicio', help_text='Unidad de medida (ej: Hora, Proyecto, Consulta, etc.)', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Si el servicio está activo y disponible')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_servicios', to='empresa.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicios',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='MaterialServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(help_text='Nombre del material o insumo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del material')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo por unidad del material', max_digits=10)),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad necesaria del material por servicio', max_digits=10)),
                ('unidad', models.CharField(default='Unidad', help_text='Unidad de medida (ej: Kg, Litros, Metros, etc.)', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='empresa.tiposervicio')),
            ],
            options={
                'verbose_name': 'Material de Servicio',
                'verbose_name_plural': 'Materiales de Servicios',
                'ordering': ['nombre'],
                'unique_together': {('tipo_servicio', 'nombre')},
            },
        ),
    ]
