# Generated by Django 5.2.3 on 2025-08-22 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0013_social_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('especial', 'Especial')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('premio_xp', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objetivo', models.TextField()),
                ('premio_xp', models.IntegerField(default=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='escenariosimulacion',
            options={'verbose_name': 'Escenario de Simulación', 'verbose_name_plural': 'Escenarios de Simulaciones'},
        ),
        migrations.AlterModelOptions(
            name='leccion',
            options={'ordering': ['modulo', 'orden'], 'verbose_name': 'Lección', 'verbose_name_plural': 'Lecciones'},
        ),
        migrations.AlterModelOptions(
            name='moduloaprendizaje',
            options={'ordering': ['tipo_empresa', 'orden'], 'verbose_name': 'Módulo de Aprendizaje', 'verbose_name_plural': 'Módulos de Aprendizaje'},
        ),
        migrations.AlterModelOptions(
            name='perfilaprendizaje',
            options={'verbose_name': 'Perfil de Aprendizaje', 'verbose_name_plural': 'Perfiles de Aprendizaje'},
        ),
        migrations.AlterModelOptions(
            name='progresousuario',
            options={'verbose_name': 'Progreso de Usuario', 'verbose_name_plural': 'Progreso de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='simulacionusuario',
            options={'verbose_name': 'Simulación de Usuario', 'verbose_name_plural': 'Simulaciones de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='tiposimulacion',
            options={'verbose_name': 'Tipo de Simulación', 'verbose_name_plural': 'Tipos de Simulaciones'},
        ),
        migrations.AlterField(
            model_name='escenariosimulacion',
            name='datos_iniciales',
            field=models.JSONField(default=dict, help_text='Datos iniciales del escenario'),
        ),
        migrations.AlterField(
            model_name='escenariosimulacion',
            name='dificultad',
            field=models.IntegerField(choices=[(1, 'Fácil'), (2, 'Medio'), (3, 'Difícil')], default=1),
        ),
        migrations.AlterField(
            model_name='escenariosimulacion',
            name='solucion_esperada',
            field=models.JSONField(default=dict, help_text='Solución correcta'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='pasos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pasocompletado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simulacionusuario',
            name='datos_entrada',
            field=models.JSONField(default=dict, help_text='Datos ingresados por el usuario'),
        ),
        migrations.AlterField(
            model_name='simulacionusuario',
            name='estado',
            field=models.CharField(choices=[('iniciada', 'Iniciada'), ('completada', 'Completada'), ('fallida', 'Fallida')], default='iniciada', max_length=20),
        ),
        migrations.AlterField(
            model_name='simulacionusuario',
            name='resultado',
            field=models.JSONField(default=dict, help_text='Resultado de la simulación'),
        ),
        migrations.AlterField(
            model_name='simulacionusuario',
            name='tiempo_completado',
            field=models.IntegerField(default=0, help_text='Tiempo en segundos'),
        ),
        migrations.AlterField(
            model_name='tiposimulacion',
            name='categoria',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('manufactura', 'Manufactura'), ('servicios', 'Servicios')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tiposimulacion',
            name='configuracion',
            field=models.JSONField(default=dict, help_text='Configuración específica de la simulación'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='contado', max_length=15),
        ),
        migrations.CreateModel(
            name='ParticipacionLiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('posicion', models.IntegerField(default=0)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.liga')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-puntos_obtenidos'],
                'unique_together': {('usuario', 'liga')},
            },
        ),
        migrations.CreateModel(
            name='ParticipacionReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.TextField(default='{}')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.reto')),
            ],
            options={
                'unique_together': {('usuario', 'reto')},
            },
        ),
    ]
