# Generated by Django 5.2.3 on 2025-08-22 20:26

from django.db import migrations

def update_iva_rates(apps, schema_editor):
    """Update existing IVA rates from 12% to 15%"""
    Venta = apps.get_model('empresa', 'Venta')
    Compra = apps.get_model('empresa', 'Compra')
    
    # Update Ventas with 12% IVA to 15%
    Venta.objects.filter(tasa_iva=12).update(tasa_iva=15)
    
    # Update Compras with 12% IVA to 15%
    Compra.objects.filter(tasa_iva=12).update(tasa_iva=15)

def reverse_iva_rates(apps, schema_editor):
    """Reverse: Update IVA rates from 15% back to 12%"""
    Venta = apps.get_model('empresa', 'Venta')
    Compra = apps.get_model('empresa', 'Compra')
    
    # Reverse: Update Ventas with 15% IVA back to 12%
    Venta.objects.filter(tasa_iva=15).update(tasa_iva=12)
    
    # Reverse: Update Compras with 15% IVA back to 12%
    Compra.objects.filter(tasa_iva=15).update(tasa_iva=12)

class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0014_gap_repair'),
    ]

    operations = [
        migrations.RunPython(update_iva_rates, reverse_iva_rates),
    ]
