# Generated by Django 5.2.3 on 2025-09-07 01:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
from django.conf import settings
# Using migrations.RenameIndex directly to avoid import resolution issues in some linters


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0017_niif_fase2'),
    ]

    operations = [
        migrations.RenameIndex(  # type: ignore[attr-defined]
            model_name='movimientoinventario',
            new_name='empresa_mov_empresa_f0e590_idx',
            old_name='empresa_mov_empresa_b8c123_idx',
        ),
        migrations.RenameIndex(  # type: ignore[attr-defined]
            model_name='movimientoinventario',
            new_name='empresa_mov_tipo_b93989_idx',
            old_name='empresa_mov_tipo_4a5678_idx',
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='transaccion_id',
            field=models.CharField(blank=True, help_text='ID único para agrupar movimientos de la misma transacción', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='Tasa de IVA (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='contratoventa',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='contratoventa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contratoventa',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='instrumentofinanciero',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='instrumentofinanciero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instrumentofinanciero',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='obligaciondesempeno',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='obligaciondesempeno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='obligaciondesempeno',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='revaluacionactivo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='revaluacionactivo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='revaluacionactivo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tasa_iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('15'), help_text='Tasa de IVA (%)', max_digits=5),
        ),
    ]
