# Generated by Django 5.2.3 on 2025-09-13 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0018_rename_empresa_mov_empresa_b8c123_idx_empresa_mov_empresa_f0e590_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='dificultad',
            field=models.IntegerField(choices=[(1, 'Fácil'), (2, 'Medio'), (3, 'Difícil')], default=1),
        ),
        migrations.AddField(
            model_name='leccion',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulacionusuario',
            name='escenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.escenariosimulacion'),
        ),
    ]
