# Generated by Django 5.2.3 on 2025-09-16 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0021_add_accounting_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='Usuario propietario de la empresa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresas_propias', to=settings.AUTH_USER_MODEL),
        ),
    ]
