# Generated by Django 5.2.3 on 2025-09-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0022_add_propietario_to_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='descripcion',
            field=models.CharField(default='Aporte de capital', max_length=100),
        ),
    ]
