# Generated by Django 5.2.3 on 2025-09-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0023_fix_capital_descripcion_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocontable',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='confirmado', help_text='Estado del asiento contable', max_length=15),
        ),
    ]
