# Generated by Django 5.2.3 on 2026-02-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0025_remove_academia_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='contado', max_length=15),
        ),
    ]
