# Generated by Django 4.2.28 on 2026-05-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0027_add_demo_fields_plan_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='transaccion_id_contable',
            field=models.CharField(blank=True, help_text='ID de la transacción contable asociada (para edición/eliminación de asientos)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gasto',
            name='transaccion_id_contable',
            field=models.CharField(blank=True, help_text='ID de la transacción contable asociada (para edición/eliminación de asientos)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='transaccion_id_contable',
            field=models.CharField(blank=True, help_text='ID de la transacción contable asociada (para edición/eliminación de asientos)', max_length=50, null=True),
        ),
    ]
