# Generated by Django 4.2.28 on 2026-05-23 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0028_add_transaccion_id_contable_to_venta_compra_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipo_operacion', models.CharField(choices=[('crear', 'Creación'), ('editar', 'Edición'), ('eliminar', 'Eliminación')], max_length=10)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='empresa.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['empresa', '-fecha'], name='empresa_reg_empresa_456687_idx'), models.Index(fields=['empresa', 'modelo'], name='empresa_reg_empresa_215773_idx'), models.Index(fields=['usuario', '-fecha'], name='empresa_reg_usuario_b38705_idx')],
            },
        ),
    ]
