# Generated by Django 4.2.28 on 2026-06-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0029_add_registro_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='poderempleado',
            name='puede_editar_compras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_editar_gastos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_editar_ventas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_eliminar_compras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_eliminar_gastos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_eliminar_productos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_eliminar_ventas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_exportar_datos',
            field=models.BooleanField(default=False, help_text='Excel/PDF/SRI ATS'),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_gestionar_clientes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_gestionar_empleados',
            field=models.BooleanField(default=False, help_text='Delegar gestión de empleados a un gerente'),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_gestionar_proveedores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_registrar_compras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='puede_ver_estados_financieros',
            field=models.BooleanField(default=False, help_text='Balance, Estado de Resultados, Flujo de Caja'),
        ),
        migrations.AddField(
            model_name='poderempleado',
            name='rol',
            field=models.CharField(choices=[('propietario', 'Propietario (acceso total)'), ('gerente', 'Gerente (todo excepto eliminar empleados)'), ('contador', 'Contador (transacciones + reportes + estados financieros)'), ('vendedor', 'Vendedor / Cajero (crear ventas + ver inventario)'), ('bodeguero', 'Bodeguero (gestión de inventario y productos)'), ('comprador', 'Comprador (compras y proveedores)'), ('auditor', 'Auditor (solo lectura: reportes + estados + actividad)'), ('personalizado', 'Personalizado (configuración manual)')], default='personalizado', max_length=20),
        ),
    ]
