# Generated by Django 5.2.3 on 2026-10-04 15:06

from django.db import migrations, models
from django.db.models import Q


def marcar_servicios_existentes(apps, schema_editor):
    """Marca como servicio lo que hasta ahora se simulaba con stock "infinito".

    - SERV-<id>: productos espejo que crea el POS para cada TipoServicio.
    - SRV*: servicios cargados en empresas de categoría servicios.
    - stock >= 99999: convención usada para "no controla stock".
    """
    Producto = apps.get_model('empresa', 'Producto')
    Producto.objects.filter(
        Q(codigo__startswith='SERV-')
        | Q(codigo__startswith='SRV', empresa__categoria='servicios')
        | Q(stock__gte=99999)
    ).update(es_servicio=True)


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0030_expandir_poderes_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_servicio',
            field=models.BooleanField(default=False, help_text='Servicio (corte, consultoría…): no maneja inventario ni costo de inventario'),
        ),
        migrations.RunPython(marcar_servicios_existentes, migrations.RunPython.noop),
    ]
