# Generated by Django 5.2.3 on 2026-10-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0032_asentar_capital_existente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(help_text='Código interno del producto (único por empresa)', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='producto_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_barras__isnull', False), models.Q(('codigo_barras', ''), _negated=True)), fields=('empresa', 'codigo_barras'), name='producto_codigo_barras_unico_por_empresa'),
        ),
    ]
