# Generated by Django 5.2.3 on 2026-10-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0034_autoria_restrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Usuario dueño de la demo (p. ej. demo_comercio)', max_length=150, unique=True)),
                ('datos', models.TextField(help_text='Objetos de la empresa serializados en JSON (django.core.serializers)')),
                ('total_objetos', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_reset', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Foto de demo',
                'verbose_name_plural': 'Fotos de demos',
            },
        ),
    ]
